// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: lint/lint.proto

package lint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LintFiles []*LintFile `protobuf:"bytes,2,rep,name=lintFiles,proto3" json:"lintFiles,omitempty"`
	LintPatch *LintPatch  `protobuf:"bytes,3,opt,name=lintPatch,proto3" json:"lintPatch,omitempty"`
}

func (x *LintRequest) Reset() {
	*x = LintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lint_lint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintRequest) ProtoMessage() {}

func (x *LintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lint_lint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintRequest.ProtoReflect.Descriptor instead.
func (*LintRequest) Descriptor() ([]byte, []int) {
	return file_lint_lint_proto_rawDescGZIP(), []int{0}
}

func (x *LintRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LintRequest) GetLintFiles() []*LintFile {
	if x != nil {
		return x.LintFiles
	}
	return nil
}

func (x *LintRequest) GetLintPatch() *LintPatch {
	if x != nil {
		return x.LintPatch
	}
	return nil
}

type LintFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *LintFile) Reset() {
	*x = LintFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lint_lint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LintFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintFile) ProtoMessage() {}

func (x *LintFile) ProtoReflect() protoreflect.Message {
	mi := &file_lint_lint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintFile.ProtoReflect.Descriptor instead.
func (*LintFile) Descriptor() ([]byte, []int) {
	return file_lint_lint_proto_rawDescGZIP(), []int{1}
}

func (x *LintFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LintFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LintPatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *LintPatch) Reset() {
	*x = LintPatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lint_lint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LintPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintPatch) ProtoMessage() {}

func (x *LintPatch) ProtoReflect() protoreflect.Message {
	mi := &file_lint_lint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintPatch.ProtoReflect.Descriptor instead.
func (*LintPatch) Descriptor() ([]byte, []int) {
	return file_lint_lint_proto_rawDescGZIP(), []int{2}
}

func (x *LintPatch) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LintPatch) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LintReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LintReports []*LintReport `protobuf:"bytes,2,rep,name=lintReports,proto3" json:"lintReports,omitempty"`
}

func (x *LintReply) Reset() {
	*x = LintReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lint_lint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LintReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintReply) ProtoMessage() {}

func (x *LintReply) ProtoReflect() protoreflect.Message {
	mi := &file_lint_lint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintReply.ProtoReflect.Descriptor instead.
func (*LintReply) Descriptor() ([]byte, []int) {
	return file_lint_lint_proto_rawDescGZIP(), []int{3}
}

func (x *LintReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LintReply) GetLintReports() []*LintReport {
	if x != nil {
		return x.LintReports
	}
	return nil
}

type LintReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File    string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line    int64  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Type    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Details string `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *LintReport) Reset() {
	*x = LintReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lint_lint_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LintReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintReport) ProtoMessage() {}

func (x *LintReport) ProtoReflect() protoreflect.Message {
	mi := &file_lint_lint_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintReport.ProtoReflect.Descriptor instead.
func (*LintReport) Descriptor() ([]byte, []int) {
	return file_lint_lint_proto_rawDescGZIP(), []int{4}
}

func (x *LintReport) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LintReport) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LintReport) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LintReport) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_lint_lint_proto protoreflect.FileDescriptor

var file_lint_lint_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x74, 0x2f, 0x6c, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6c, 0x69, 0x6e, 0x74, 0x22, 0x7e, 0x0a, 0x0b, 0x4c, 0x69, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x6c, 0x69,
	0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6c, 0x69, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x09, 0x6c,
	0x69, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x74,
	0x50, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x69,
	0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x63, 0x68, 0x52, 0x09, 0x6c, 0x69,
	0x6e, 0x74, 0x50, 0x61, 0x74, 0x63, 0x68, 0x22, 0x38, 0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x39, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x74, 0x50, 0x61, 0x74, 0x63, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x53, 0x0a, 0x09,
	0x4c, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a,
	0x0b, 0x6c, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x69, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x0b, 0x6c, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x22, 0x62, 0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x32, 0x3d, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x74, 0x12, 0x11,
	0x2e, 0x6c, 0x69, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0f, 0x2e, 0x6c, 0x69, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x6f, 0x70, 0x73, 0x2d, 0x6c, 0x69, 0x6e, 0x74, 0x66, 0x6c,
	0x6f, 0x77, 0x2f, 0x6c, 0x69, 0x6e, 0x74, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x6c, 0x69, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lint_lint_proto_rawDescOnce sync.Once
	file_lint_lint_proto_rawDescData = file_lint_lint_proto_rawDesc
)

func file_lint_lint_proto_rawDescGZIP() []byte {
	file_lint_lint_proto_rawDescOnce.Do(func() {
		file_lint_lint_proto_rawDescData = protoimpl.X.CompressGZIP(file_lint_lint_proto_rawDescData)
	})
	return file_lint_lint_proto_rawDescData
}

var file_lint_lint_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lint_lint_proto_goTypes = []interface{}{
	(*LintRequest)(nil), // 0: lint.LintRequest
	(*LintFile)(nil),    // 1: lint.LintFile
	(*LintPatch)(nil),   // 2: lint.LintPatch
	(*LintReply)(nil),   // 3: lint.LintReply
	(*LintReport)(nil),  // 4: lint.LintReport
}
var file_lint_lint_proto_depIdxs = []int32{
	1, // 0: lint.LintRequest.lintFiles:type_name -> lint.LintFile
	2, // 1: lint.LintRequest.lintPatch:type_name -> lint.LintPatch
	4, // 2: lint.LintReply.lintReports:type_name -> lint.LintReport
	0, // 3: lint.LintProto.SendLint:input_type -> lint.LintRequest
	3, // 4: lint.LintProto.SendLint:output_type -> lint.LintReply
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lint_lint_proto_init() }
func file_lint_lint_proto_init() {
	if File_lint_lint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lint_lint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lint_lint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LintFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lint_lint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LintPatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lint_lint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LintReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lint_lint_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LintReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lint_lint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lint_lint_proto_goTypes,
		DependencyIndexes: file_lint_lint_proto_depIdxs,
		MessageInfos:      file_lint_lint_proto_msgTypes,
	}.Build()
	File_lint_lint_proto = out.File
	file_lint_lint_proto_rawDesc = nil
	file_lint_lint_proto_goTypes = nil
	file_lint_lint_proto_depIdxs = nil
}
