apiVersion: v1
kind: server
metadata:
  name: lintflow
spec:
  lint:
    - name: lintcpp
      host: 127.0.0.1
      port: 9090
      timeout: 300
      filter:
        include:
          extension:
            - .c
            - .cc
            - .cpp
            - .h
            - .hpp
          file:
            - message
          repo:
            - foo
    - name: lintjava
      host: 127.0.0.1
      port: 9091
      timeout: 300
      filter:
        include:
          extension:
            - .java
            - .xml
          file:
            - message
          repo:
            - foo
    - name: lintpython
      host: 127.0.0.1
      port: 9092
      timeout: 300
      filter:
        include:
          extension:
            - .py
          file:
            - message
          repo:
            - foo
    - name: lintshell
      host: 127.0.0.1
      port: 9093
      timeout: 300
      filter:
        include:
          extension:
            - .sh
          file:
            - message
          repo:
            - foo
  review:
    - name: gerrit
      host: http://127.0.0.1/
      port: 8080
      user: user
      pass: pass
      vote:
        approval: +1
        disapproval: -1
        label: Code-Review
        message: Voting Code-Review by lintflow
